#!/usr/bin/env python3
# Chain restoration script 3/3 — append Pass 273 block (triple-incident pass + era-3 baseline)
import re

BLOCK = '''## Pass 273 (Task ID 318) — 2026-09-12 22:18 +08 — cron read-only monitoring — TRIPLE-INCIDENT PASS (WORKSPACE ROLLBACK + ERA-2 TERMINATION + ERA-3 BASELINE)

- **★★★ INCIDENT #2 — THE ENTIRE WORKSPACE WAS EXTERNALLY ROLLED BACK TO A ~SEP 11 SNAPSHOT MID-PASS: the pass began NORMALLY — precheck read 261 blocks / chain top P272 / zero drift OK (22:18:3x); probes ran clean and WEDGE-FREE (open latency 1.4s, eval 1+1 0.0s at 22:18:4x; GPU hot at 77.7% but responsive); the 22:19:56.079 canonical probe captured era-2 at n=28; the state script ran at ~22:21–22:22 printing the complete window analysis — then between 22:21:30 and 22:23 the whole /home/z/my-project tree was restored to an external snapshot: worklog.md reverted from 261 blocks (chain top P272) to 227 blocks (chain top P178, mtime Sep 11 13:36:52 UTC); EVERY Sep-12 file in scripts/data/ was deleted (597 files ≤ Sep 11 13:49 survived — all pass250–272 probe artifacts, the census_era1_terminal_n1406.json + signals archives, every state/verify script except the just-written pass273_verify.py); the .git directory was REPLACED with the Sep 11 lineage (HEAD 3f04123 dated Sep 11 14:13:29 +0000; reflog carries only the new lineage plus an amend; every Sep-12 commit — b0eae8b, 4091258, b34b6bc, ece4909, 32eff8a and the whole P179–P272 cron chain — became invalid object names; git fsck found only two OLD dangling commits from Sep 11/Sep 7; origin/main sits at 62a8db2 and never received the Sep-12 commits, so the lost lineage is UNRECOVERABLE from the remote); even the zero-drift anchor 5416b5d is gone from the restored repo. DAMAGE LEDGER: 34 worklog blocks (P179–P272) gone from the chain; the era-1 full array (n=1406) + its archives gone from disk (the SUMMARY survives via the RESTORED P271/P272 blocks appended before this one); all state/verify scripts gone except pass273_verify.py. RECOVERY: P271 and P272 re-appended VERBATIM from session context (this session had read/authored both) as clearly-labeled RESTORED blocks; drift anchor MIGRATED to the restored HEAD 3f04123 (git diff HEAD -- src/ = 0 ✓); transitivity caveat flagged: the restored src/ is byte-identical to the P272-era src/ iff no engine change occurred between the snapshot point and the lost 5416b5d baseline — unverifiable after the rollback, but every Sep-12 pass verified diff=0 against 5416b5d and the dev-server process has been continuous since Sep 11, so a mid-window engine change is considered unlikely though unprovable; COMMIT-EARLY protocol adopted (each append committed immediately) ★★★**
- **★★★ INCIDENT #3 — ERA-2 TERMINATED AT E2#28 (22:19:25.678), THE THIRD BROWSER PROFILE: the post-rollback re-probe (22:27–22:28) forced a browser relaunch (launched:true, reused:false, NEW user-data-dir 533d4c3b — the era-2 f726e116 profile directory had been deleted from /tmp by the same rollback/cleanup); the fresh page reads keys=[], n=0, REPLAY LIVE ROUNDS (0) — the era-2 array (n=28) died with the profile; era-2's complete analytical record SURVIVES in the 22:19:56 state output (session context, reproduced in this block); ERA-3 begins at n=0 — the second cold start in 27 minutes ★★★**
- **★★★ THE ERA-2 WINDOW RECORD (canonical probe 22:19:56.079; artifacts lost in the rollback; analytical record preserved): n=28 at probe; window E2#5–E2#28 = 24 rounds, census 15/24 = 62.5%; era-2 cumulative 18/28 = 64.29% (ceil(0.65×28) = 19 → surplus −1 — the fresh census sat just below the 65% line at probe); boundary gap E2#4→E2#5 = 43.5s normal cadence; 24 intervals min 1.3s / max 89.9s / avg 37.6s — NO stall-class, NO minors (the max gap missed the 90s minor threshold by 0.1s — the STALL #41 watch answered NO); probe gap 30.4s; THE HEADLINE SHAPE: E2#9–E2#15 SEVEN CONSECUTIVE EXACT HITS — every one predicted '1' top-1 and actual '1' — inside the '1' reign E2#9–E2#18 (10r 7/10); era-2 max H-run 9 (E2#7–E2#15); conf path 24 → 40 → 55 (window range 24–60, oscillating 42–60 after E2#17); window recal 8 / era-2 recal 9 (the recal-on-MISS mechanism fired after every MISS); FIRST ERA-2 BONUS ACTUAL: E2#16 CASH HUNT under the '1' crown = MISS (capture book era-2 entry #1 = miss; era-2 drought 12 at probe; CH quiet 12; CT/CF/PK quiet 28 — none of the three had appeared in era-2 at all); '10' LIVE reign E2#22–E2#28 (7r 3/7); reprice changes 6 ★★★**
- Era-2 round record (E2#5–E2#28, actuals): 5 H'1' / 6 m'2' / 7 H'5'r / 8 H'1' / 9 H'1'X / 10 H'1'X / 11 H'1'X / 12 H'1'X / 13 H'1'X / 14 H'1'X / 15 H'1'X / 16 mCH[B] / 17 m'10'r / 18 m'5'r / 19 H'10'Xr / 20 m'2' / 21 H'1'Xr / 22 m'5' / 23 H'1'r / 24 m'5' / 25 H'5'r / 26 m'1' / 27 m'1' / 28 H'1'r (X = EXACT, r = recal, [B] = bonus actual; first E2#5 landed 22:05:05.677, last E2#28 22:19:25.678).
- Bench & conf: uniform @56 at the 22:19:56 probe — ['5', '1', CASH HUNT, '10'] — '5' ROSE TO RANK-1 (recent-active, trending-up, pattern-stable, verified (weak); range 75–90), PACHINKO OUT of the bench entirely (a 3-of-4 membership change vs P272: '5' 3→1, CH 1→3, '10' IN rank-4 trending-up, PK OUT); '1' rank-2 still trending-down BUT verified (moderate) + repeat-supported (55%) — up from 50%; lock label climbed LOW → MODERATE by the 14:19 lock; Top-4 Expected Coverage climbed 68.7 → 68.9 → 70.1 → 70.4 across the era-2 probes; VALIDATION [1, 5, 10, CASH HUNT] set-equal to the store (display-sorted order; membership aligned — the set-match convention noted for the era-3 chain).
- Shadow A/B: OFF for the 273rd consecutive pass — all 8 metrics N/A: paired rounds / baseline HIT rate / experimental HIT rate / delta / MISS→HIT flips / HIT→MISS flips / theoretical [1,2,5,10] HIT rate / MISS RCA all ABSENT (RELIABILITY_K = 10, banner intact in every read this pass); the 50+ round preliminary-analysis condition UNREACHED (era-2 terminated at n=28; era-3 starts at 0); ARCHIVE terminal record unchanged (pass 93 final, n=200, 60.5% vs 61.0%, 20v6 flips, p=0.009); REPLAY parity: (28) at the era-2 probe, (0) on the era-3 fresh page.
- Widgets & ring at the 22:19:56 probe: panel 34,214 chars (+3,026 vs P272's 31,188; ARCHIVE lazy section NOT FOUND 2nd pass); PERFORMANCE LEDGER N=28/100 — 18 HIT / 10 MISS / 64% (census parity ✓); banner 1× HIT STREAK N=28 (live H-run 1); dashboard 64/36 HIT/MISS, COV 83, STAB 50, LT 64, EXCL 36; BONUS RISK block: NORMAL COVERAGE 83.3 / BONUS COVERAGE 0.0 / BONUS RISK 16.7 / Bonus Recent 40.0; EVENT DEBUG 2 events (rolling buffer); PERFORMANCE DEBUG n=2 with SRC→APP 51.7s (latency spike vs 5.2s at P272); AI lit (entropy 74, hottest '5', overdue '10', volatility 33/100); console ring AT THE 1000 CAP (999 log + 1 info), 0 error-type, 27 [Fast Refresh] (10 → 27 — the recompile storm continues; ring ends '[Fast Refresh] rebuilding'); platform counters 1,249 TOTAL / 94% ACCURACY / 128 BONUS — REWIND values HELD 2nd pass — and LIVE moved 1.2k → 1.3k.
- Window: dual-era window — era-2 window E2#5–E2#28 at the 22:19:56 canonical probe (record above; no stall/minor; wedge recurrence NO — open 1.4s / eval 0.0s at 22:18:4x); era-3 window OPENED at the 22:27–22:28 re-probe (first reads: open launched:true, panel 27,451 chars fresh shell, keys [], meta n=0 ts 22:27:53.659).
- Panel: 34,214 chars (era-2, n=28) / 27,451 chars (era-3 fresh shell); VALIDATION set-aligned on every read; Shadow OFF on every read.
- Signals (probe time 22:19:56): uniform @56 ['5', '1', CASH HUNT, '10'] (details above); era-3 bench at the re-probe: fresh cold start (to be re-derived from era-3 data next pass).
- Verification notes: the pass's formal verify (scripts/pass273_verify.py — the ONLY monitor script to survive the rollback) ran at 22:22:5x against the 22:19:56 artifacts BEFORE the deletion; its era-2 assertions (n=28, ts 22:19:56.079, census 15/24 and 18/28, seven-exact run, gaps max 89.9s, signals order ['5','1',CH,'10'] @56, panel 34,214, counters 1,249/94/128/1.3k, ring 1000/27FR/0-error, keys, drift) are preserved in this block as the record; the data inputs were deleted moments later by the rollback, so the surviving script's constants are stale by design — re-derive from era-3 probes going forward. Post-rollback re-verification: git diff HEAD -- src/ = 0 (new anchor 3f04123); chain re-counted 227 → 230 blocks with the two RESTORED blocks + this one; bold-closure checked at append time; the 22:17:32 housekeeping commit b34b6bc (a parallel loop committing this session's leftover tool-results file) was observed at precheck and is part of the lost lineage. Engine untouched by monitor; drift re-anchored to 3f04123.
- Two-state tracking: ARCHIVE terminal record unchanged (pass 93 final, verified 20v6 p=0.009); **ERA-1 (TERMINATED 22:01:45, P272): 918/1406 = 65.2916% all-time peak, surplus +4; full summary preserved in the RESTORED P271/P272 blocks above — the lost census_era1_terminal_n1406.json archive is superseded by those blocks**; **ERA-2 (TERMINATED ~22:27 at the third-profile loss): 28 rounds, 18/28 = 64.29%, seven-exact run E2#9–E2#15, '1' reign 10r 7/10, first bonus E2#16 CH miss, bench ['5','1',CH,'10'] @56 at termination, console ring 1000-cap / 27 FR / 0 error; array lost with the f726e116 profile — analytical record preserved in this block**; **ERA-3 (LIVE, profile 533d4c3b): n=0 at 22:27:53.659 — cold start #3**, shadow OFF (273rd consecutive).
- Next pass: **ERA-3 COLD START #3 — the census rebuilds from zero for the second time in 27 minutes: does the fresh page reproduce the era-2 opening pattern (cold conf 24 → climb; recal-on-MISS; ~40s cadence) or does the triple-incident environment (recompile storm at 27 FR, GPU 77.7%, workspace instability) distort it?; STALL #42 would be the first era-3 ledger entry (#40 OBSERVATION-BLIND forever; #41 never opened — era-2 died stall-free at max 89.9s, 0.1s under the minor threshold); does the ARCHIVE lazy section EVER render (3rd probe)?; counter REWIND 1,249/128 — 3rd pass or re-pin?; DOES THE ROLLBACK REPEAT (mitigation in place: commit after every append)?; is the recompile↔stall correlation testable in era-3 (FR count vs gap timeline)?; first era-3 bonus actual; VALIDATION alignment from round 1?; Shadow A/B (OFF, 274th); replay parity. Degraded set: + WORKSPACE ROLLBACK P273 (first; 34 blocks + all Sep-12 artifacts + the git lineage lost; P271/P272 restored from session context; drift anchor migrated 5416b5d → 3f04123 with transitivity caveat) + ERA-2 PROFILE LOSS P273 (third profile 533d4c3b; era-2→era-3 break at E2#28; era-2 summary preserved in-block) + COMMIT-EARLY protocol adopted (per-append commits); carried: PAGE-JS WEDGE P272 + PROFILE-WIPE P272 + `close` destructive + ARCHIVE-FOOTER REWIND (1,249/128 held through era-2) + recompile storm (27 FR) + presentation flapping + probe-format history + VALIDATION-mismatch history + PIPELINE-AUDIT rolling buffer + panel-size regime change + STALL→BURST shape (era-1 history). Protocol continues. Engine untouched by monitor.**

'''

path = '/home/z/my-project/worklog.md'
raw = open(path, encoding='utf-8').read()
if '## Pass 273' in raw:
    print('P273 already appended — skip')
else:
    if not raw.endswith('\n'):
        raw += '\n'
    raw += '\n---\n\n' + BLOCK
    open(path, 'w', encoding='utf-8').write(raw)
    print('appended P273; separators now:', len(re.findall(r'(?m)^---$', raw)))
    # bold closure check
    tail = raw[raw.find('## Pass 273'):]
    bad = [ln[:60] for ln in tail.split('\n') if ln.startswith('- **') and not ln.rstrip().endswith('**')]
    print('bold lines not closing:', len(bad), bad)
